// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUtsgneHgLkjDMyP_1QJ-V-Fn0zoQwQs8',
    appId: '1:396377642704:web:ea8c42d5db3992cfa1b0d5',
    messagingSenderId: '396377642704',
    projectId: 'kidzke24',
    authDomain: 'kidzke24.firebaseapp.com',
    storageBucket: 'kidzke24.appspot.com',
    measurementId: 'G-0Z9D5DESPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB43jyWGxPndAKaOlfiHD7wJFi6fFPVvMg',
    appId: '1:396377642704:android:8cb72e24edb6530ea1b0d5',
    messagingSenderId: '396377642704',
    projectId: 'kidzke24',
    storageBucket: 'kidzke24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSLaIT_OaYo5L2Psza4-znbX7We4VHGHE',
    appId: '1:396377642704:ios:ed44e810c5cf4508a1b0d5',
    messagingSenderId: '396377642704',
    projectId: 'kidzke24',
    storageBucket: 'kidzke24.appspot.com',
    androidClientId: '396377642704-monugdcu37bk98l7tnkgrd6rpnl7htci.apps.googleusercontent.com',
    iosBundleId: 'com.example.zubi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSLaIT_OaYo5L2Psza4-znbX7We4VHGHE',
    appId: '1:396377642704:ios:ed44e810c5cf4508a1b0d5',
    messagingSenderId: '396377642704',
    projectId: 'kidzke24',
    storageBucket: 'kidzke24.appspot.com',
    androidClientId: '396377642704-monugdcu37bk98l7tnkgrd6rpnl7htci.apps.googleusercontent.com',
    iosBundleId: 'com.example.zubi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUtsgneHgLkjDMyP_1QJ-V-Fn0zoQwQs8',
    appId: '1:396377642704:web:1da4efc3a4489c59a1b0d5',
    messagingSenderId: '396377642704',
    projectId: 'kidzke24',
    authDomain: 'kidzke24.firebaseapp.com',
    storageBucket: 'kidzke24.appspot.com',
    measurementId: 'G-758ZRMB3G8',
  );
}
